@extends('storefront.layouts.theme')

@section('content')
@include('storefront.themes.glow-rose.partials.top-bar')
@include('storefront.themes.glow-rose.partials.hero')
@include('storefront.themes.glow-rose.partials.sticky-nav')
@include('storefront.themes.glow-rose.partials.about')
@include('storefront.partials.dynamic.services')
@include('storefront.partials.dynamic.packages')
@include('storefront.themes.glow-rose.partials.relaxation')
@include('storefront.themes.glow-rose.partials.special-offer')
@include('storefront.partials.dynamic.staff')
@include('storefront.themes.glow-rose.partials.premium-banner')
@include('storefront.partials.dynamic.locations')
@include('storefront.partials.dynamic.testimonials')
@include('storefront.themes.glow-rose.partials.footer-info-cards')
@include('storefront.themes.glow-rose.partials.footer')
@endsection
